#!/usr/bin/env python3
"""
gen_dividers.py — write layers/04-dividers.svg.

Geometry is derived, not placed by eye: the leg tips ARE the two ends of the
ring's break (ellipse (450, 830), rx 230, ry 52, at 15° and 45°), so if the
ring moves the instrument follows. The hinge hangs on a gold shaft that leaves
the sun's disc along the sun→hinge line.
"""
import math

SUN, SUN_R = (450, 300), 118
RING = (450, 830, 230, 52)
HINGE = (586, 596)


def on_ring(deg):
    cx, cy, rx, ry = RING
    t = math.radians(deg)
    return cx + rx*math.cos(t), cy + ry*math.sin(t)


def unit(a, b):
    dx, dy = b[0]-a[0], b[1]-a[1]
    L = math.hypot(dx, dy)
    return dx/L, dy/L, L


def leg(h, tip, w_hinge, w_tip):
    """Tapered quad from hinge to tip."""
    ux, uy, _ = unit(h, tip)
    nx, ny = -uy, ux
    pts = [(h[0]+nx*w_hinge/2, h[1]+ny*w_hinge/2), (tip[0]+nx*w_tip/2, tip[1]+ny*w_tip/2),
           (tip[0]-nx*w_tip/2, tip[1]-ny*w_tip/2), (h[0]-nx*w_hinge/2, h[1]-ny*w_hinge/2)]
    return "M " + " L ".join(f"{x:.1f},{y:.1f}" for x, y in pts) + " Z"


def main():
    tA, tB = on_ring(15), on_ring(45)
    ux, uy, _ = unit(SUN, HINGE)
    edge = (SUN[0]+ux*SUN_R, SUN[1]+uy*SUN_R)             # where the shaft leaves the disc
    fin = (HINGE[0]-ux*30, HINGE[1]-uy*30)                # finial ring centre
    shaft_end = (fin[0]-ux*6, fin[1]-uy*6)
    # tapered shaft: 9 wide at the disc, 2.5 at the finial
    shaft = leg(edge, shaft_end, 9, 2.5)
    aA = math.degrees(math.atan2(tA[1]-HINGE[1], tA[0]-HINGE[0]))
    aB = math.degrees(math.atan2(tB[1]-HINGE[1], tB[0]-HINGE[0]))
    R = 118                                                # quadrant arc radius
    a0, a1 = math.radians(aA - 3), math.radians(aB + 5)
    arc = (f"M {HINGE[0]+R*math.cos(a0):.1f},{HINGE[1]+R*math.sin(a0):.1f} "
           f"A {R} {R} 0 0 1 {HINGE[0]+R*math.cos(a1):.1f},{HINGE[1]+R*math.sin(a1):.1f}")
    svg = f'''  <defs>
    <linearGradient id="brass" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#F3DDA4"/><stop offset="1" stop-color="#B4843C"/>
    </linearGradient>
    <linearGradient id="beam" gradientUnits="userSpaceOnUse"
        x1="{edge[0]:.1f}" y1="{edge[1]:.1f}" x2="{fin[0]:.1f}" y2="{fin[1]:.1f}">
      <stop offset="0" stop-color="#FFF6D6" stop-opacity="0.95"/>
      <stop offset="1" stop-color="#F7D98A" stop-opacity="0.55"/>
    </linearGradient>
    <filter id="glow" x="-50%" y="-50%" width="200%" height="200%">
      <feGaussianBlur stdDeviation="5"/>
    </filter>
  </defs>

  <!-- The measure: a gold shaft leaves the disc at ({edge[0]:.1f}, {edge[1]:.1f}) and holds a
       pair of wing dividers by the finial. Hinge ({HINGE[0]}, {HINGE[1]}); tips land exactly on
       the ends of the ring's break: A ({tA[0]:.1f}, {tA[1]:.1f}) at 15°, B ({tB[0]:.1f}, {tB[1]:.1f}) at 45°.
       Leg angles {aA:.1f}° / {aB:.1f}° — a {aB-aA:.1f}° spread. Generated by gen_dividers.py. -->
  <g clip-path="url(#field)" stroke-linejoin="round">
    <!-- shaft: light, not a rod — glow plus a core that fades from the disc
         toward the finial, no ink outline (iter 014's inked rod made the sun
         read as a lollipop held up by the dividers) -->
    <path d="{shaft}" fill="#FFE8A8" opacity="0.75" filter="url(#glow)"/>
    <path d="{shaft}" fill="url(#beam)"/>

    <!-- quadrant arc between the legs (what makes these dividers, not two sticks) -->
    <path d="{arc}" fill="none" stroke="#2B1E14" stroke-width="5" stroke-linecap="round"/>
    <path d="{arc}" fill="none" stroke="#D8B66C" stroke-width="2.6" stroke-linecap="round"/>

    <!-- legs: brass, inked, tapering to needle points -->
    <g fill="url(#brass)" stroke="#2B1E14" stroke-width="1.4">
      <path d="{leg(HINGE, tB, 11, 1.2)}"/>
      <path d="{leg(HINGE, tA, 11, 1.2)}"/>
    </g>

    <!-- finial ring and hinge boss -->
    <circle cx="{fin[0]:.1f}" cy="{fin[1]:.1f}" r="6.5" fill="none" stroke="#2B1E14" stroke-width="4"/>
    <circle cx="{fin[0]:.1f}" cy="{fin[1]:.1f}" r="6.5" fill="none" stroke="#E9C877" stroke-width="2"/>
    <line x1="{fin[0]+ux*6.5:.1f}" y1="{fin[1]+uy*6.5:.1f}" x2="{HINGE[0]-ux*11:.1f}" y2="{HINGE[1]-uy*11:.1f}" stroke="#2B1E14" stroke-width="4" stroke-linecap="round"/>
    <circle cx="{HINGE[0]}" cy="{HINGE[1]}" r="12" fill="url(#brass)" stroke="#2B1E14" stroke-width="1.6"/>
    <circle cx="{HINGE[0]}" cy="{HINGE[1]}" r="3" fill="#2B1E14"/>
  </g>
'''
    open("layers/04-dividers.svg", "w").write(svg)
    print("tips", tA, tB, "spread", aB - aA)


if __name__ == "__main__":
    main()
