#!/usr/bin/env python3
"""
gen_clouds.py — write layers/02-clouds.svg.

Method (from iter 009; see process-log for the three failed passes before it):
soft colour-printed masses, not outlined bubbles. Each cluster is a scatter of
circles inside a rotated ellipse, drawn twice under a Gaussian blur: a dark
body, then a smaller warm crest shifted toward the sun. Ink is spent only on
a few tapered swirls. Seeded, so the file rebuilds identically.
"""
import math
import random

rng = random.Random(1794)  # Songs of Experience
SUN = (450, 300)

# (cx, cy, half-width, half-height, rotation°, n circles, darkness 0-1)
CLUSTERS = [
    (178, 410, 150, 62, -24, 60, 1.0),   # left mass, rising toward the sun
    (728, 392, 140, 58, 22, 56, 1.0),    # right mass, mirrored but not equal
    (452, 522, 300, 40, 0, 90, 0.9),     # low bank the sun's foot sinks into
    (150, 150, 110, 34, 18, 26, 0.7),    # top-left wisp
    (770, 140, 100, 30, -16, 22, 0.6),   # top-right wisp
]


def scatter(cx, cy, a, b, rot, n):
    """n circles inside a rotated ellipse; radii larger near the centre."""
    th = math.radians(rot)
    out = []
    for _ in range(n):
        u, v = rng.uniform(-1, 1), rng.uniform(-1, 1)
        if u*u + v*v > 1:
            u, v = u*0.7, v*0.7
        x, y = u*a, v*b
        r = (1 - 0.55*math.hypot(u, v)) * b * rng.uniform(0.8, 1.35)
        out.append((cx + x*math.cos(th) - y*math.sin(th), cy + x*math.sin(th) + y*math.cos(th), r))
    return out


def toward_sun(x, y, d):
    dx, dy = SUN[0] - x, SUN[1] - y
    L = math.hypot(dx, dy) or 1
    return x + dx/L*d, y + dy/L*d


def swirl(cx, cy, r, turns, direction, start, w0):
    """A tapered spiral as a filled ribbon: width w0 at the outside → 0."""
    steps = int(60 * turns)
    left, right = [], []
    for i in range(steps + 1):
        f = i / steps
        a = start + direction * 2*math.pi*turns*f
        rr = r * (1 - 0.8*f)
        w = w0 * (1 - f)
        x, y = cx + rr*math.cos(a), cy + rr*math.sin(a)
        nx, ny = math.cos(a), math.sin(a)
        left.append(f"{x + nx*w/2:.1f},{y + ny*w/2:.1f}")
        right.append(f"{x - nx*w/2:.1f},{y - ny*w/2:.1f}")
    return "M " + " L ".join(left + right[::-1]) + " Z"


SWIRLS = [
    swirl(250, 372, 30, 1.5, 1, 2.6, 4.2),
    swirl(650, 356, 28, 1.5, -1, 0.5, 4.0),
    swirl(96, 452, 26, 1.3, -1, 0.2, 3.4),
    swirl(812, 430, 24, 1.3, 1, 3.0, 3.2),
]


def circles(cs, fill, opacity):
    rows = "\n".join(f'      <circle cx="{x:.1f}" cy="{y:.1f}" r="{r:.1f}"/>' for x, y, r in cs)
    return f'    <g fill="{fill}" opacity="{opacity}" filter="url(#soft)">\n{rows}\n    </g>'


def main():
    out = ['''  <defs>
    <!-- Soft edge for colour-printed masses. Region padded so the blur isn't clipped. -->
    <filter id="soft" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur stdDeviation="11"/>
    </filter>
  </defs>

  <!-- Clouds (generated by gen_clouds.py — edit there, not here) -->
  <g clip-path="url(#field)">''']
    for cx, cy, a, b, rot, n, dark in CLUSTERS:
        body = scatter(cx, cy, a, b, rot, n)
        # Crest: small, pushed well toward the sun, faint — a lit rim, not a lid.
        # (iter 009: at 0.55 r and 0.45 r offset it covered the body and left
        # dark rings, so every mass read hollow.)
        crest = [(*toward_sun(x, y, r*0.8), r*0.3) for x, y, r in body]
        out.append(f"    <!-- cluster at ({cx}, {cy}) -->")
        out.append(circles(body, "#2E2850", round(0.88*dark, 2)))
        out.append(circles(crest, "#E9BE95", round(0.4*dark, 2)))
    # Swirls removed at iter 011: placed independently of the masses, they
    # floated on top as stuck-on hooks. Ink is kept for the instrument,
    # the ring and the figure. swirl() stays for reuse; SWIRLS is unused.
    out.append('  </g>\n')
    open("layers/02-clouds.svg", "w").write("\n".join(out))


if __name__ == "__main__":
    main()
